params:
  samples: "samples.tsv"
  metadata: "samples_metadata.tsv"


  # https://docs.qiime2.org/2024.2/data-resources/
  database:
    taxonomy_classifiers:
      silva_138_99_OTUs_full_length_sequences:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/silva-138-99-nb-classifier.qza"
      diverse_weighted_silva_138_99_OTUs_full_length_sequences:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/silva-138-99-nb-diverse-weighted-classifier.qza"
      human_stool_weighted_silva_138_99_OTUs_full_length_sequences:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/silva-138-99-nb-human-stool-weighted-classifier.qza"

      gtdb_classifier_r220:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/gtdb_classifier_r220.qza"
      diverse_weighted_gtdb_classifier_r220:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/gtdb_diverse_weighted_classifier_r220.qza"
      human_stool_weighted_gtdb_classifier_r220:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/gtdb_human_stool_weighted_classifier_r220.qza"

      greengenes2_2024.09_full_length_sequences:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/2024.09.backbone.full-length.nb.sklearn-1.4.2.qza"
      greengenes2_2024.09_from_515F_806R_region_of_sequences:
        "/databases/ecogenomics/QIIME2/2024.5/taxonomic_classifier/2024.09.backbone.v4.nb.sklearn-1.4.2.qza"


  # https://docs.qiime2.org/2023.9/tutorials/importing/
  import:
    type: "SampleData[PairedEndSequencesWithQuality]"
    # EMPSingleEndSequences
    # EMPPairedEndSequences
    # MultiplexedSingleEndBarcodeInSequence
    # MultiplexedPairedEndBarcodeInSequence
    # SampleData[SequencesWithQuality]
    # SampleData[PairedEndSequencesWithQuality]
    # FeatureTable[Frequency]
    # Phylogeny[Unrooted]

    format: "PairedEndFastqManifestPhred33V2"
    # CasavaOneEightSingleLanePerSampleDirFmt
    # SingleEndFastqManifestPhred33V2
    # SingleEndFastqManifestPhred64V2
    # PairedEndFastqManifestPhred33V2
    # PairedEndFastqManifestPhred64V2
    # BIOMV100Format
    # BIOMV210Format

  denoise:
    threads: 8
    dada2:
      do: True
      paired:
        trunc_len_f: 280
        trunc_len_r: 250
        trim_left_f: 0
        trim_left_r: 0
      single:
        trunc_len: 120
        trim_left: 0
    deblur:
      do: False
      trim_len: 280
      left_trim_len: 0

  taxonomic:
    threads: 8
    classifiers: ["silva_138_99_OTUs_full_length_sequences"]
      # silva_138_99_OTUs_full_length_sequences
      # diverse_weighted_silva_138_99_OTUs_full_length_sequences
      # human_stool_weighted_silva_138_99_OTUs_full_length_sequences
      # gtdb_classifier_r220
      # diverse_weighted_gtdb_classifier_r220
      # human_stool_weighted_gtdb_classifier_r220
      # greengenes2_2024.09_full_length_sequences
      # greengenes2_2024.09_from_515F_806R_region_of_sequences

  phylotree:
    threads: 8
    sepp_db: /home/jiezhu/databases/ecogenomics/QIIME2/2023.9/sepp_reference_databases/sepp-refs-silva-128.qza
    # /home/jiezhu/databases/ecogenomics/QIIME2/2023.9/sepp_reference_databases/sepp-refs-gg-13-8.qza

  function:
    threads: 8


output:
  tmp: "results/tmp"
  database: "results/00.database"
  import: "results/00.import"
  denoise: "results/01.denoise"
  taxonomic: "results/02.taxonomic"
  phylotree: "results/03.phylotree"
  function: "results/04.function"


envs:
  qiime2: "envs/qiime2.yaml"
  picrust2: "envs/picrust2.yaml"
